/**
 * testnet4Account tests — derivation parity with bao.markets is the core
 * contract: the vectors below were generated by running the markets
 * implementation (`packages/markets/services/testnet/TestnetOnChainWallet.ts`)
 * on this machine (2026-09-22). If any of these break, the two apps have
 * split one wallet into two — do not update the vectors, fix the code.
 */
import { describe, expect, it } from 'vitest';
import { hex } from '@scure/base';
import { p2tr, Transaction, TEST_NETWORK } from '@scure/btc-signer';
import { PendingSpentTracker } from '../angorPatterns';
import {
  deriveTestnet4Account,
  estimateTestnet4Vsize,
  generateTestnet4Mnemonic,
  importTestnet4AccountFromMnemonic,
  scanTestnet4Utxos,
  sendTestnet4,
  testnet4AddressAt,
} from './testnet4Account';

const BASE = 'https://mempool.space/testnet4/api';
const MNEMONIC =
  'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about';
const SESSION_SECRET = '11'.repeat(32);

// ── fetch fixtures ───────────────────────────────────────────────────────────

const json = (body: unknown): Response =>
  ({ ok: true, status: 200, json: async () => body, text: async () => JSON.stringify(body) }) as unknown as Response;
const text = (body: string, status = 200): Response =>
  ({ ok: status >= 200 && status < 300, status, json: async () => ({}), text: async () => body }) as unknown as Response;

function fetchFor(routes: Record<string, () => Response>): typeof fetch {
  const fn = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
    const url = String(input);
    const method = (init?.method ?? 'GET').toUpperCase();
    const key = `${method} ${url}`;
    const route = routes[key] ?? routes[url];
    if (!route) throw new Error(`unexpected fetch: ${key}`);
    return route();
  };
  return fn as unknown as typeof fetch;
}

const fees = () =>
  json({ fastestFee: 2, halfHourFee: 2, hourFee: 1, economyFee: 1, minimumFee: 1 });

// ── derivation parity ────────────────────────────────────────────────────────

describe('testnet4Account — markets parity vectors', () => {
  it('derives the same session addresses as bao.markets', () => {
    const account = deriveTestnet4Account(SESSION_SECRET);
    expect(testnet4AddressAt(account, 0, 0).address).toBe('tb1q3ejchc0s0st9rnzlry0m3fgc9j6vgwat3tq5ts');
    expect(testnet4AddressAt(account, 0, 1).address).toBe('tb1q8fg9f2w2ygt3pkn5xqfpcheurpkkrmaycum64a');
    expect(testnet4AddressAt(account, 1, 0).address).toBe('tb1qkw0amvz2emprekzspk8m7kgycmjrfng6m5q42y');
    expect(testnet4AddressAt(account, 0, 0).path).toBe("m/84'/1'/0'/0/0");
    expect(account.source).toBe('session');
  });

  it('derives the same mnemonic addresses as bao.markets', () => {
    const account = importTestnet4AccountFromMnemonic(MNEMONIC);
    expect(testnet4AddressAt(account, 0, 0).address).toBe('tb1q6rz28mcfaxtmd6v789l9rrlrusdprr9pqcpvkl');
    expect(testnet4AddressAt(account, 0, 1).address).toBe('tb1qd7spv5q28348xl4myc8zmh983w5jx32cjhkn97');
    expect(testnet4AddressAt(account, 0, 2).address).toBe('tb1qxdyjf6h5d6qxap4n2dap97q4j5ps6ua8sll0ct');
    expect(testnet4AddressAt(account, 1, 0).address).toBe('tb1q9u62588spffmq4dzjxsr5l297znf3z6j5p2688');
    expect(account.source).toBe('imported');
  });

  it('normalizes whitespace/case and rejects invalid mnemonics', () => {
    const account = importTestnet4AccountFromMnemonic(`  ${MNEMONIC.toUpperCase()}  `);
    expect(testnet4AddressAt(account, 0, 0).address).toBe('tb1q6rz28mcfaxtmd6v789l9rrlrusdprr9pqcpvkl');
    expect(() => importTestnet4AccountFromMnemonic('abandon abandon abandon')).toThrow(/Invalid mnemonic/);
  });

  it('generates 12- and 24-word mnemonics that import', () => {
    const m12 = generateTestnet4Mnemonic(12);
    const m24 = generateTestnet4Mnemonic(24);
    expect(m12.split(' ')).toHaveLength(12);
    expect(m24.split(' ')).toHaveLength(24);
    expect(() => importTestnet4AccountFromMnemonic(m12)).not.toThrow();
    expect(() => importTestnet4AccountFromMnemonic(m24)).not.toThrow();
  });

  it('rejects a malformed session secret', () => {
    expect(() => deriveTestnet4Account('11'.repeat(31))).toThrow(/64 lowercase hex/);
    expect(() => deriveTestnet4Account('ab'.repeat(32).toUpperCase())).toThrow(/64 lowercase hex/);
  });
});

// ── UTXO scan ────────────────────────────────────────────────────────────────

describe('testnet4Account — UTXO scan', () => {
  it('tags UTXOs with chain/index/script and filters dust-ish inputs', async () => {
    const account = deriveTestnet4Account(SESSION_SECRET);
    const receive0 = testnet4AddressAt(account, 0, 0).address;
    const change0 = testnet4AddressAt(account, 1, 0).address;
    const routes: Record<string, () => Response> = {};
    for (let i = 0; i < 7; i++) {
      const addr = testnet4AddressAt(account, 0, i).address;
      routes[`${BASE}/address/${addr}/utxo`] = () =>
        i === 0
          ? json([
              { txid: 'aa'.repeat(32), vout: 0, value: 5000, status: { confirmed: true, block_height: 10 } },
              { txid: 'bb'.repeat(32), vout: 1, value: 200, status: { confirmed: true, block_height: 11 } },
            ])
          : json([]);
    }
    for (let i = 0; i < 7; i++) {
      const addr = testnet4AddressAt(account, 1, i).address;
      routes[`${BASE}/address/${addr}/utxo`] = () =>
        i === 0
          ? json([{ txid: 'cc'.repeat(32), vout: 2, value: 7000, status: { confirmed: false, block_height: null } }])
          : json([]);
    }
    const utxos = await scanTestnet4Utxos(account, { receiveIndex: 1, changeIndex: 1, fetchFn: fetchFor(routes), baseUrl: BASE });
    expect(utxos).toHaveLength(2);
    const recv = utxos.find((u) => u.txid === 'aa'.repeat(32));
    const chg = utxos.find((u) => u.txid === 'cc'.repeat(32));
    expect(recv).toMatchObject({ address: receive0, chain: 0, index: 0, value: 5000 });
    expect(recv?.script).toBeInstanceOf(Uint8Array);
    expect(chg).toMatchObject({ address: change0, chain: 1, index: 0, value: 7000 });
  });

  it('fails loudly when an address fetch fails — balance is never a guess', async () => {
    const account = deriveTestnet4Account(SESSION_SECRET);
    const routes: Record<string, () => Response> = { [`${BASE}/address/${testnet4AddressAt(account, 0, 0).address}/utxo`]: () => text('', 500) };
    await expect(
      scanTestnet4Utxos(account, { receiveIndex: 0, changeIndex: 0, fetchFn: fetchFor(routes), baseUrl: BASE }),
    ).rejects.toThrow(/HTTP 500/);
  });
});

// ── send ─────────────────────────────────────────────────────────────────────

describe('testnet4Account — send', () => {
  const account = deriveTestnet4Account(SESSION_SECRET);
  const receive0 = testnet4AddressAt(account, 0, 0).address;
  const spent = { txid: 'aa'.repeat(32), vout: 0, value: 100_000, status: { confirmed: true, block_height: 100 } };

  function sendRoutes(overrides: Record<string, () => Response> = {}): Record<string, () => Response> {
    const routes: Record<string, () => Response> = {};
    for (let i = 0; i < 5; i++) {
      const addr = testnet4AddressAt(account, 0, i).address;
      routes[`${BASE}/address/${addr}/utxo`] = () => (addr === receive0 ? json([spent]) : json([]));
    }
    for (let i = 0; i < 5; i++) {
      const addr = testnet4AddressAt(account, 1, i).address;
      routes[`${BASE}/address/${addr}/utxo`] = () => json([]);
    }
    routes[`${BASE}/v1/fees/recommended`] = fees;
    routes[`POST ${BASE}/tx`] = () => text('cd'.repeat(32));
    return { ...routes, ...overrides };
  }

  it('builds, signs and broadcasts; change goes to the change chain', async () => {
    const reserved = new PendingSpentTracker();
    const dest = p2tr(new Uint8Array(32).fill(2), undefined, TEST_NETWORK).address!;
    const res = await sendTestnet4(account, {
      to: dest,
      sats: 50_000,
      feeTier: 'hour',
      receiveIndex: 0,
      changeIndex: 0,
      reserved,
      fetchFn: fetchFor(sendRoutes()),
      baseUrl: BASE,
      nowSeconds: Math.floor(Date.now() / 1000),
    });
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    expect(res.txid).toBe('cd'.repeat(32));
    expect(res.usedInputs).toEqual([`${spent.txid}:0`]);
    expect(res.changeAddress).toBe(testnet4AddressAt(account, 1, 0).address);
    // 1 input, P2TR destination (43 vB) + P2WPKH change (31 vB) + 11 overhead = 153 vB @ 1 sat/vB
    expect(res.feeSats).toBe(estimateTestnet4Vsize(1, { destinationVsize: 43, withChange: true }));
    expect(res.feeSats).toBe(153);
    expect(res.changeAddress).toBeTruthy();

    const parsed = Transaction.fromRaw(hex.decode(res.rawTx));
    expect(parsed.inputsLength).toBe(1);
    expect(parsed.outputsLength).toBe(2);
    expect(parsed.getOutput(0).amount).toBe(50_000n);
    expect(parsed.getOutput(1).amount).toBe(BigInt(100_000 - 50_000 - res.feeSats));
    expect(reserved.keys().map((k) => k.key)).toEqual([`${spent.txid}:0`]);
  });

  it('rolls dust change into the fee instead of creating an unspendable output', async () => {
    const dust = { txid: 'ee'.repeat(32), vout: 0, value: 50_400, status: { confirmed: true, block_height: 100 } };
    const routes = sendRoutes();
    routes[`${BASE}/address/${receive0}/utxo`] = () => json([dust]);
    const res = await sendTestnet4(account, {
      to: testnet4AddressAt(account, 0, 3).address,
      sats: 50_000,
      receiveIndex: 0,
      changeIndex: 0,
      fetchFn: fetchFor(routes),
      baseUrl: BASE,
    });
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    expect(res.changeAddress).toBeNull();
    expect(res.feeSats).toBe(400);
    const parsed = Transaction.fromRaw(hex.decode(res.rawTx));
    expect(parsed.outputsLength).toBe(1);
    expect(parsed.getOutput(0).amount).toBe(50_000n);
  });

  it('refuses non-testnet4 and cross-network destinations', async () => {
    const bc1 = 'bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4';
    const liquid = 'tex1qsxp05t96708chlu4ksrken0c77ha9teyjxqfcl';
    for (const to of [bc1, liquid]) {
      const res = await sendTestnet4(account, {
        to,
        sats: 1000,
        receiveIndex: 0,
        changeIndex: 0,
        fetchFn: fetchFor(sendRoutes()),
        baseUrl: BASE,
      });
      expect(res.ok).toBe(false);
      if (!res.ok) expect(res.code).toBe('invalid_address');
    }
  });

  it('fails closed when the fee estimate is unavailable', async () => {
    const routes = sendRoutes({ [`${BASE}/v1/fees/recommended`]: () => text('', 503) });
    const res = await sendTestnet4(account, {
      to: testnet4AddressAt(account, 0, 3).address,
      sats: 1000,
      receiveIndex: 0,
      changeIndex: 0,
      fetchFn: fetchFor(routes),
      baseUrl: BASE,
    });
    expect(res.ok).toBe(false);
    if (!res.ok) expect(res.code).toBe('fee_estimate_failed');
  });

  it('returns insufficient-funds without a UTXO', async () => {
    const routes = sendRoutes();
    routes[`${BASE}/address/${receive0}/utxo`] = () => json([]);
    const res = await sendTestnet4(account, {
      to: testnet4AddressAt(account, 0, 3).address,
      sats: 1000,
      receiveIndex: 0,
      changeIndex: 0,
      fetchFn: fetchFor(routes),
      baseUrl: BASE,
    });
    expect(res.ok).toBe(false);
    if (!res.ok) expect(res.code).toBe('insufficient_funds');
  });

  it('reports a mapped broadcast failure and does not reserve inputs', async () => {
    const reserved = new PendingSpentTracker();
    const routes = sendRoutes({ [`POST ${BASE}/tx`]: () => text('txn-mempool-conflict', 400) });
    const res = await sendTestnet4(account, {
      to: testnet4AddressAt(account, 0, 3).address,
      sats: 50_000,
      receiveIndex: 0,
      changeIndex: 0,
      reserved,
      fetchFn: fetchFor(routes),
      baseUrl: BASE,
    });
    expect(res.ok).toBe(false);
    if (!res.ok) {
      expect(res.code).toBe('broadcast_failed');
      expect(res.message).toMatch(/conflicting spend/i);
    }
    expect(reserved.keys()).toHaveLength(0);
  });

  it('rejects amounts that are not positive integers', async () => {
    for (const sats of [0, -1, 1.5, Number.NaN]) {
      const res = await sendTestnet4(account, {
        to: testnet4AddressAt(account, 0, 3).address,
        sats,
        receiveIndex: 0,
        changeIndex: 0,
        fetchFn: fetchFor(sendRoutes()),
        baseUrl: BASE,
      });
      expect(res.ok).toBe(false);
      if (!res.ok) expect(res.code).toBe('invalid_amount');
    }
  });
});
