import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import {
  canonicalJson,
  canonicalHash,
  ledgerEntryPrevHash,
  genesisPrevHash,
  proofSetHash,
  utf8Compare,
  type ProofMeta,
} from './baoLedger';
import { merkleLeafHash, merkleRoot, merkleProof, merkleVerify } from './baoMerkle';

/**
 * Row-B conformance fixture - INDEPENDENT VECTORS (row-B decisions B2/B3).
 *
 * Literals generated by `scripts/vectors/gen_canonical_merkle_vectors.py`:
 * a pure-Python re-derivation of the frozen §1.5/§5.6 rules (recursive
 * UTF-8-byte-order key sort, NFC, ints-only JSON; 0x00/0x01-prefixed blake3
 * tree) using the BLAKE3 team's pure-Python reference hash - NO TS/JS in the
 * generation path, and the Python blake3 passes the official BLAKE3 test
 * vectors (input_len 0..102400) before emitting a single fixture.
 *
 * Contract: if THIS test fails, either the TS implementation or the
 * generator has a bug against the frozen spec. Investigate against the spec
 * text; NEVER regenerate the fixture to make a failing test pass without an
 * explicit spec-amendment review (see scripts/vectors/README.md).
 */
const here = dirname(fileURLToPath(import.meta.url));
const VECTORS = JSON.parse(
  readFileSync(join(here, '__tests__', 'fixtures', 'canonicalMerkle.vectors.json'), 'utf8'),
) as {
  meta: Record<string, string>;
  canonical_json: Array<{ purpose: string; input: unknown; canonical: string; hash: string }>;
  ledger_prevhash: Array<{
    entry: { seq: number; created_at: number; event_id: string; content: unknown };
    canonical_bytes_hex: string;
    prevHash: string;
  }>;
  genesis_prevhash: Array<{ aCoordinate: string; prevHash: string }>;
  proof_set_hash: Array<{
    proofs: Array<{ secretCommit: string; mint: string; tier: string | null; deadlineMs: number | null }>;
    per_proof_hashes: string[];
    proofSetHash: string;
  }>;
  merkle: Array<{
    name: string;
    leaves?: Array<{ n: string; sats: number }>;
    preimage_hex?: string;
    leaf_hash?: string;
    leaf_hashes_sorted?: string[];
    root: string;
  }>;
};

// Provenance must ship inside the fixture file itself.
expect(VECTORS.meta.independence).toContain('no TS/JS');

describe('canonical JSON - independent literals (row B)', () => {
  it.each(VECTORS.canonical_json)('$purpose', (vec) => {
    expect(canonicalJson(vec.input)).toBe(vec.canonical);
    expect(canonicalHash(vec.input)).toBe(vec.hash);
  });

  it('sorts keys by UTF-8 BYTES (the committed literal pins the rule)', () => {
    const case1 = VECTORS.canonical_json[0];
    // "Alpha" (41…), "e" (65), "zeta" (7A…), "é" (C3 A9): byte order puts
    // é LAST even though its code point (E9) is below "zeta" (7A…).
    expect(case1.canonical).toBe('{"Alpha":2,"e":4,"zeta":1,"é":3}');
    expect(canonicalJson(case1.input)).toBe(case1.canonical);
  });

  it('folds NFD input to NFC bytes (committed literal)', () => {
    const nfd = VECTORS.canonical_json[2];
    expect(nfd.canonical).toBe('"été"');
    // Rebuild the NFD input from its recorded code points (e + U+0301 ...).
    const rebuilt = String.fromCodePoint(
      ...(nfd as unknown as { input_nfd_codepoints: string[] }).input_nfd_codepoints.map((h) => parseInt(h, 16)),
    );
    expect(canonicalJson(rebuilt)).toBe('"été"');
  });

  it('rejects what the spec forbids (floats, cyclic, non-plain objects)', () => {
    expect(() => canonicalJson({ x: 1.5 })).toThrow(/float/);
    const cyc: Record<string, unknown> = {};
    cyc['self'] = cyc;
    expect(() => canonicalJson(cyc)).toThrow(/cyclic/);
    expect(() => canonicalJson(new Date())).toThrow(/plain objects/);
  });

  it('utf8Compare orders by UTF-8 bytes, not code points', () => {
    // é = C3 A9 > z = 7A by bytes, but E9 < 7A is false by code point too -
    // the distinguishing pair is U+FF21 (EF BC A1) vs "a" (61): bytes sort
    // "a" first; naive code-unit compare would ALSO sort "a" first, so the
    // byte-level rule is pinned by the multi-plane committed literal above.
    expect(utf8Compare('a', '\uFF21')).toBeLessThan(0);
    expect(utf8Compare('\uFF21', 'a')).toBeGreaterThan(0);
    expect(utf8Compare('z', 'é')).toBeLessThan(0);
    expect(utf8Compare('é', 'z')).toBeGreaterThan(0);
  });
});

describe('ledger prevHash - independent literals (row B)', () => {
  it.each(VECTORS.ledger_prevhash)('entry seq=$entry.seq', (vec) => {
    expect(ledgerEntryPrevHash(vec.entry)).toBe(vec.prevHash);
  });

  it('includes ALL FOUR fields (no nonce-field elision, §5.6 amend 4)', () => {
    const vec = VECTORS.ledger_prevhash[0];
    // The canonical bytes are committed: if an elision regression drops
    // event_id or content, the hash AND the byte dump both diverge.
    const canonical = canonicalJson(vec.entry);
    expect(Buffer.from(vec.canonical_bytes_hex, 'hex').toString('utf8')).toBe(canonical);
    expect(canonical).toContain('"event_id"');
    expect(canonical).toContain('"content"');
  });
});

describe('genesis prevHash - independent literals (row B)', () => {
  it.each(VECTORS.genesis_prevhash)('$aCoordinate', (vec) => {
    expect(genesisPrevHash(vec.aCoordinate)).toBe(vec.prevHash);
  });
});

describe('proofSetHash - independent literals (row B)', () => {
  it('sorts by per-element canonical hash, then hashes the canonical array', () => {
    const vec = VECTORS.proof_set_hash[0];
    const proofs: ProofMeta[] = vec.proofs.map((p) => ({
      secretCommit: p.secretCommit,
      mint: p.mint,
      tier: p.tier,
      deadlineMs: p.deadlineMs,
    }));
    expect(proofSetHash(proofs)).toBe(vec.proofSetHash);
    // Sorting is order-independent: shuffle in, same hash out.
    const shuffled = [...proofs].reverse();
    expect(proofSetHash(shuffled)).toBe(vec.proofSetHash);
  });
});

describe('Merkle accumulator - independent literals (row B)', () => {
  it('leaf preimage bytes are pinned (0x00 || canonical {n,sats})', () => {
    const leaf = VECTORS.merkle[0];
    expect(leaf.name).toBe('leaf_preimage');
    const preimage = Buffer.from(leaf.preimage_hex as string, 'hex');
    expect(preimage[0]).toBe(0x00);
    expect(preimage.subarray(1).toString('utf8')).toBe('{"n":"' + '1'.repeat(64) + '","sats":1000}');
    expect(merkleLeafHash({ n: '1'.repeat(64), sats: 1000 })).toBe(leaf.leaf_hash);
  });

  it('empty tree root is the public blake3 empty-input vector', () => {
    const empty = VECTORS.merkle.find((m) => m.name === 'empty');
    expect(empty?.root).toBe('af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262');
    expect(merkleRoot([])).toBe(empty?.root);
  });

  it.each(
    VECTORS.merkle.filter((m) => m.leaves !== undefined),
  )('tree "$name" roots to the committed literal', (tree) => {
    const leaves = (tree.leaves as Array<{ n: string; sats: number }>).map((l) => ({ n: l.n, sats: l.sats }));
    expect(merkleRoot(leaves)).toBe(tree.root);
    // Order-independence: same SET, different input order → same root.
    if (leaves.length > 1) {
      expect(merkleRoot([...leaves].reverse())).toBe(tree.root);
    }
    // Leaf hashes sort ascending (committed order).
    if (tree.leaf_hashes_sorted) {
      const recomputed = leaves.map((l) => merkleLeafHash(l)).sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
      expect(recomputed).toEqual(tree.leaf_hashes_sorted);
    }
  });

  it('inclusion proofs verify against the committed roots (odd-promotion path included)', () => {
    for (const tree of VECTORS.merkle) {
      if (!tree.leaves || tree.leaves.length === 0) continue;
      const leaves = tree.leaves.map((l) => ({ n: l.n, sats: l.sats }));
      for (let i = 0; i < leaves.length; i++) {
        const proof = merkleProof(leaves, i);
        expect(merkleVerify(tree.root, leaves[i], proof), `${tree.name}[${i}]`).toBe(true);
      }
    }
  });

  it('tamper check: a mutated proof must NOT verify', () => {
    const tree = VECTORS.merkle.find((m) => m.name === 'three_odd_promotion');
    const leaves = (tree as { leaves: Array<{ n: string; sats: number }> }).leaves;
    const proof = merkleProof(leaves, 0);
    const bad: typeof proof = { ...proof, siblings: [...proof.siblings] };
    if (bad.siblings[0] != null) {
      bad.siblings[0] = 'f'.repeat(64);
      expect(merkleVerify((tree as { root: string }).root, leaves[0], bad)).toBe(false);
    }
  });
});
